In [1]:
import tensorflow as tf 

# 张量限幅操作
## 避免张量的值过大或者过小
clip_by_value操作(例如relu操作)

clip_by_norm操作

gradient clip操作

In [9]:
# 数据剪裁操作
a = tf.random.normal([3,2])
print(a)
tf.maximum(a,0)
# 这里其实是一个relu函数

tf.Tensor(
[[ 1.5634894  0.7554021]
 [-1.014851   2.1200325]
 [-0.7073716  0.9214353]], shape=(3, 2), dtype=float32)


<tf.Tensor: id=49, shape=(3, 2), dtype=float32, numpy=
array([[1.5634894, 0.7554021],
       [0.       , 2.1200325],
       [0.       , 0.9214353]], dtype=float32)>

In [10]:
tf.nn.relu(a)

<tf.Tensor: id=50, shape=(3, 2), dtype=float32, numpy=
array([[1.5634894, 0.7554021],
       [0.       , 2.1200325],
       [0.       , 0.9214353]], dtype=float32)>

In [11]:
tf.minimum(0,a)

<tf.Tensor: id=52, shape=(3, 2), dtype=float32, numpy=
array([[ 0.       ,  0.       ],
       [-1.014851 ,  0.       ],
       [-0.7073716,  0.       ]], dtype=float32)>

In [12]:
tf.clip_by_value(a,-0.5,0.5)
# 将数据限制在-0.5到0.5之间,超限的用-0.5或者0.5代替

<tf.Tensor: id=56, shape=(3, 2), dtype=float32, numpy=
array([[ 0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5]], dtype=float32)>

In [13]:
tf.clip_by_value(tf.range(9),3,7)

<tf.Tensor: id=64, shape=(9,), dtype=int32, numpy=array([3, 3, 3, 3, 4, 5, 6, 7, 7])>

In [17]:
# 范数缩放限幅, 有利于在矩阵各个方向上进行相同幅度的限幅, 避免造成矩阵的方向变化(梯度方向的变化)
b = tf.random.normal([2,2],mean=10)
print(b)



tf.Tensor(
[[ 9.411928   7.9117823]
 [10.062585   9.734371 ]], shape=(2, 2), dtype=float32)


In [18]:
tf.norm(b)

<tf.Tensor: id=103, shape=(), dtype=float32, numpy=18.63315>

In [19]:
tf.clip_by_norm(b,15)
# 15代表范数缩放的系数

<tf.Tensor: id=120, shape=(2, 2), dtype=float32, numpy=
array([[7.576761, 6.369118],
       [8.10055 , 7.836333]], dtype=float32)>

In [21]:
tf.norm(tf.clip_by_norm(b,15))
# 哪找范数缩放后的矩阵的范数就是之前设置的缩放系数

<tf.Tensor: id=164, shape=(), dtype=float32, numpy=14.999999>

#### 梯度裁剪,避免梯度爆炸和梯度消失/弥散
使用clip_by_global_norm, 范数系数一般设置10-30的数字

保证要求梯度个各个参数的缩放程度是相同的, 保证梯度下降的程度相同(避免, 一个参数缩放了1倍, 另一个参数缩放了20倍这种情况)

### 在训练过程中可以观察梯度的范数, 如果范数在10到20之间, 比较正常, 如果太大或者太小都对训练不利, 容易导致梯度爆炸或者梯度弥散, 这种情况下就需要对梯度的全局范数裁剪(保证等比例裁剪)