In [1]:
import tensorflow as tf 

In [7]:
a = tf.linspace(-6.,6.,10)

In [8]:
# sigmoid函数将数据归一化到0到1之间 

tf.sigmoid(a)

<tf.Tensor: id=13, shape=(10,), dtype=float32, numpy=
array([0.00247264, 0.00931597, 0.03444517, 0.11920291, 0.33924365,
       0.6607564 , 0.8807971 , 0.96555483, 0.99068403, 0.9975274 ],
      dtype=float32)>

In [9]:
  # 将所有节点数据归一化到0到1并保证所有节点的值之和为1
    tf.nn.softmax(a)
    # 输出的所有的值都在0到1之间, 而且所有值的和为1
    
    # 这个函数可以方法数据中的大小比值, 打的更大, 小的更小, 所以叫softmax(软性放大 )

<tf.Tensor: id=14, shape=(10,), dtype=float32, numpy=
array([4.5246225e-06, 1.7164924e-05, 6.5118002e-05, 2.4703599e-04,
       9.3717274e-04, 3.5553225e-03, 1.3487710e-02, 5.1167920e-02,
       1.9411403e-01, 7.3640394e-01], dtype=float32)>

In [12]:
 sample = tf.random.uniform([1,10],minval=-2,maxval=2)
 sample

<tf.Tensor: id=29, shape=(1, 10), dtype=float32, numpy=
array([[ 0.22111034, -1.7015052 ,  0.77100945,  0.09290552,  1.5321136 ,
        -0.37176895, -0.5335989 ,  1.7109485 ,  1.780788  , -0.7167311 ]],
      dtype=float32)>

In [13]:
tf.nn.softmax(sample)

<tf.Tensor: id=30, shape=(1, 10), dtype=float32, numpy=
array([[0.05531926, 0.00808901, 0.09587261, 0.04866287, 0.20522858,
        0.03057681, 0.0260082 , 0.24541712, 0.26316965, 0.02165594]],
      dtype=float32)>

In [16]:
# 另一种方法, tanh, 将数据保证在-1到1之间
b = tf.range(-2.,3.)

In [17]:
tf.tanh(b)

<tf.Tensor: id=42, shape=(5,), dtype=float32, numpy=
array([-0.9640276, -0.7615942,  0.       ,  0.7615942,  0.9640276],
      dtype=float32)>