In [1]:
import tensorflow as tf 
import numpy as np


### 通用索引方式

In [7]:
a = tf.ones([1,5,5,3])
a[0][0]
# 获得一个矩阵

<tf.Tensor: id=66, shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
a[0][0][0]
# 获得一个向量

<tf.Tensor: id=78, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [9]:
a[0][0][0][2]
# 获得一个标量

<tf.Tensor: id=94, shape=(), dtype=float32, numpy=1.0>

#### numpy格式的索引

In [10]:
b = tf.random.normal([4,28,28,3])

b.shape

TensorShape([4, 28, 28, 3])

In [11]:
b[1].shape
# 读取一层索引

TensorShape([28, 28, 3])

In [12]:
b[1,3].shape
# 两层索引

TensorShape([28, 3])

In [13]:
b[1,2,3,2].shape
# 四层索引, 获得一个标量

TensorShape([])

## 切片操作

In [15]:
c = tf.range(18)
c

<tf.Tensor: id=120, shape=(18,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])>

In [16]:
c[-1:]
# 切片操作和numpy基本一样

<tf.Tensor: id=124, shape=(1,), dtype=int32, numpy=array([17])>

In [17]:
c[3:5]

<tf.Tensor: id=128, shape=(2,), dtype=int32, numpy=array([3, 4])>

In [18]:
c[:-1]

<tf.Tensor: id=132, shape=(17,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])>

In [ ]:
# 多维矩阵也可以实现切片操作

In [19]:
d = tf.random.normal([3,25,25,4])

In [21]:
d[1,20,20:,2:]
# 多维的切片操作

<tf.Tensor: id=146, shape=(5, 2), dtype=float32, numpy=
array([[ 1.2873585 ,  0.28682515],
       [ 1.2462889 , -0.13766177],
       [ 0.2551482 , -2.399497  ],
       [ 1.0355536 ,  0.88264173],
       [ 0.97955227, -1.9931513 ]], dtype=float32)>

In [23]:
d[1,15,20:]
# 切片操作一部分矩阵
# 最后一维没有写, 相当于取全部

<tf.Tensor: id=153, shape=(5, 4), dtype=float32, numpy=
array([[ 0.09219573, -2.0436275 ,  2.1420934 ,  1.1256727 ],
       [ 1.4276824 , -0.79754376,  0.211269  , -0.40515053],
       [-0.46248397,  0.20963521, -0.12933134, -0.1319697 ],
       [-0.47681817, -0.2714438 ,  0.16907796,  0.2211754 ],
       [ 1.063781  ,  1.4049748 ,  0.57715386,  1.4489008 ]],
      dtype=float32)>

In [25]:
d[1,20,15:,:]
# 最后一维写:,相当于取全部

<tf.Tensor: id=161, shape=(10, 4), dtype=float32, numpy=
array([[ 0.82799816,  0.03751003,  0.616271  ,  0.3717033 ],
       [-0.17510365,  0.720787  , -1.2335621 ,  0.31483352],
       [ 0.56112367,  2.092395  , -1.540277  ,  0.8558799 ],
       [ 0.45571506, -0.05418962,  0.5806122 ,  2.5256934 ],
       [-0.05601694,  1.8163462 , -1.4260166 ,  0.298168  ],
       [ 0.7502643 , -0.32371765,  1.2873585 ,  0.28682515],
       [-0.3987965 , -0.14649075,  1.2462889 , -0.13766177],
       [ 0.84489596,  0.925131  ,  0.2551482 , -2.399497  ],
       [ 0.70748305,  0.46639317,  1.0355536 ,  0.88264173],
       [-0.24988315,  1.20537   ,  0.97955227, -1.9931513 ]],
      dtype=float32)>

In [27]:
d[1,24,24,:].shape

TensorShape([4])

In [28]:
d[1,].shape

TensorShape([25, 25, 4])

In [29]:
d[1,:,:,:].shape

TensorShape([25, 25, 4])

In [30]:
d[1,24,].shape

TensorShape([25, 4])

In [31]:
d[1,24,:,:].shape

TensorShape([25, 4])

In [32]:
d[:,:,:,2].shape

TensorShape([3, 25, 25])

In [33]:
d[:,2,:,:].shape

TensorShape([3, 25, 4])

#### 间隔采样切片操作

In [38]:
# 间隔采样切片操作
# 采样操作变为了 start:end:step
d[:,::2,::2,:].shape

TensorShape([3, 13, 13, 4])

In [39]:
d[1,2,::2,3].shape

TensorShape([13])

In [40]:
d[:,1:20:2,0:21:2,3].shape

TensorShape([3, 10, 11])

#### 冒号实现倒序的功能, 使用负的step

In [44]:
e = tf.range(4)
e

<tf.Tensor: id=233, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [43]:
e[::-1]
# 从末尾进行倒序的间隔为1的采样

<tf.Tensor: id=229, shape=(4,), dtype=int32, numpy=array([3, 2, 1, 0])>

In [45]:
e[::-2]
# 从末尾进行倒序的间隔为2的采样

<tf.Tensor: id=237, shape=(2,), dtype=int32, numpy=array([3, 1])>

In [46]:
e[2::-2]
# 从索引2位置开始进行倒序的间隔为2的采样

<tf.Tensor: id=241, shape=(2,), dtype=int32, numpy=array([2, 0])>

In [55]:
e[3:0:-2]
# 倒序操作的话, 相应的start也是起始:终止这样的格式, 就是说start的值要大于end

<tf.Tensor: id=279, shape=(2,), dtype=int32, numpy=array([3, 1])>

#### ...(三个点)符号实现多个连续维度的完整采样的功能
系统会自动识别相应的维度
这些维度必须是连续的, 只有连续的才能逻辑上推断出哪些是省略的操作

In [47]:
f = tf.random.normal([3,5,6,7])

In [48]:
f[1,...].shape
# 这里...相当于上面的后面三维数据全部选择:,:,:

TensorShape([5, 6, 7])

In [49]:
f[1,...,1].shape

TensorShape([5, 6])

In [50]:
f[...,1].shape

TensorShape([3, 5, 6])

## selective index
### 按照自定义顺序进行采样

In [ ]:
# 按照一定的随意顺序, 按照这个随意顺序进行采样

In [59]:
data = tf.ones([3,25,8],dtype = tf.float32)
# 3个维度分别是 班级,学生数量, 科目
# 想在要对这些数据进行打乱

In [70]:
tf.gather(data,axis=0,indices=[0,2]).shape 
# axis = 0代表只去第一个维度的,indices代表要取的索引
# 按照班级维度进行采样


TensorShape([2, 25, 8])

#### 这里即使数组索引超限也不会报错

In [67]:
tf.gather(data,axis=0,indices=[2,0,1]).shape 
# 按照班级维度进行采样
# 实现了非顺序采样

TensorShape([3, 25, 8])

In [73]:
tf.gather(data,axis=1,indices=[2,0,1,17, 9, 8, 3]).shape 
# 按照学生维度进行采样

TensorShape([3, 7, 8])

In [75]:
tf.gather(data,axis=2,indices=[2,0,1,7,3]).shape
# 按照科目维度进行采样

TensorShape([3, 25, 5])

#### 另一种采样方法
适应于各种采样, 定制化采样
tf.gather_nd(data,[]), 这个[]作为最外层的维度锁定, 具体怎么采样看这个方括号内是怎么组合的
方括号内的组合方式必须是同一纬度的,例如: [[1,2],[2,3]] 或者[[2,3,2],[2,3,1]] 或者 [2,3]\

下面这种是错误的:
[[1,2],[2,3,2]]或者[2,[3,2]]


注意:
[[[2,3,2],[2,3,1]]]
和
[[2,3,2],[2,3,1]]
这两种都可以实现, 但是他们的shape是不同的, 分别是TensorShape([1,2])和TensorShape([2])
#### 一般建议使用两层[],这样最终得到的都是至少是个矩阵, 而不是向量或者标量

In [76]:
tf.gather_nd(data,[0]).shape # 这里在第一个维度上取了0 ,相当于取了第一个班级

TensorShape([25, 8])

In [78]:
tf.gather_nd(data,[0,1]).shape 
# 这里在第一个维度上取了0 ,在第二个维度上取了1,相当于取了第一个班级的第二个学生

TensorShape([8])

In [80]:
tf.gather_nd(data, [0,1,2]).shape 
# 这里在第一个维度上取了0 ,在第二个维度上取了1,, 第三个维度上取了2, 
# 相当于取了第一个班级的第二个学生的第三门成绩
# 也就是一个标量

TensorShape([])

In [81]:
tf.gather_nd(data, [[0,1,2]]).shape 
# 这里在第一个维度上取了0 ,在第二个维度上取了1,, 第三个维度上取了2, 
# 但是嵌套了2层方括号
# 相当于取了第一个班级的第二个学生的第三门成绩
# 也就是一个标量的数组, 也就是一个向量

TensorShape([1])

In [82]:
tf.gather_nd(data, [[0,1,2],[1,3,2]]).shape 
# 这里在第一个维度上取了0 ,在第二个维度上取了1,, 第三个维度上取了2, 
# 这里在第一个维度上取了1 ,在第二个维度上取了3,, 第三个维度上取了2, 
# 相当于取了第一个班级的第二个学生的第三门成绩
# 和第二个班级的第四个学生的第三门成绩
# 组成了一个向量
# 也就是一个标量的数组, 也就是一个向量

TensorShape([2])

In [83]:
tf.gather_nd(data, [[0,1],[1,3]]).shape 
# 这里在第一个维度上取了0 ,在第二个维度上取了1,
# 这里在第一个维度上取了1 ,在第二个维度上取了3, 
# 相当于取了第一个班级的第二个学生的所有成绩 - 长度为8
# 和第二个班级的第四个学生的所有成绩 - 长度为8
# 组成了一个tensor
# 也就是一个标量的数组, 也就是一个矩阵(l两个长度为8的tensor组成一个2*8的tensor)

TensorShape([2, 8])

#### 根据true或者false进行索引的切片操作
tf.boolean_mask()

In [88]:
data_4mask = tf.ones([4,28,28,3])


tf.boolean_mask(data_4mask,mask=[True,True,False,False]).shape 
# 这里True和False代表获取或者跳过
# [True,True,False,False] 就相当于获取 0和1索引的, 跳过2和3索引的,
# 这里没有设置axis,而且只有一层[]说明是在
# 最外层的索引进行的操作

TensorShape([2, 28, 28, 3])

In [90]:
tf.boolean_mask(data_4mask,mask=[True,True,False],axis=3).shape 
# 这里相当于是一个在axis = 3的维度上取了index为0和1的所有数据, 而跳过了index是2的数据

TensorShape([4, 28, 28, 2])

In [94]:
data_4mask_bool = tf.ones([2,3,4])

tf.boolean_mask(data_4mask_bool,mask=[[True, True, False],[False, False,True]]).shape

# 这里mask参数传入的是两层的[],说明代表的是两维的数据, 也就是说[2,3,4]维度中对应了[2,3]
# 所以,如上边, 我们传入的True/False的数组也是一个2*3的大小的数据
# 取出来的, 第一部分[True, True, False]是在data_4mask_bool[0]这个3*4大小的矩阵中
# 获取第一行和第二行,跳过第三行
# 第一部分[False, False,True]是在data_4mask_bool[1]这个3*4大小的矩阵中
# 获取第三行, 跳过第一行和第二行
# 所以最终得到的是一个3*4大小的矩阵

TensorShape([3, 4])