In [1]:
import tensorflow as tf 

# 数据的填充和复制
填充pad
复制tile(以及之前将的broadcast_to)

## 数据填充

In [3]:
a = tf.random.normal([2])

In [6]:
tf.pad(a,[[3,2]]).shape
# 这里第二个参数是两层[],第一层[]代表各个维度, 第二层[]代表这个维度上两个方向的pad长度, 这里相当于是在a的一个维度上进行左边3个padding, 右边2个padding

TensorShape([7])

In [7]:
b = tf.random.normal([3,4])

In [8]:
tf.pad(b,[[1,0],[0,1]])

<tf.Tensor: id=24, shape=(4, 5), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.3233648 ,  0.15780583,  0.8687261 ,  0.4064283 ,  0.        ],
       [ 2.0178568 , -0.81621975, -2.5033035 , -0.76135814,  0.        ],
       [-0.72688043, -0.18983746,  0.71761984,  0.8353507 ,  0.        ]],
      dtype=float32)>

In [10]:
# image的padding
c = tf.random.normal([4,28,28,3])
tf.pad(c,[[0,0],# 图片数量不进行padding
         [1,1],# 高度方向进行上下各1的padding
         [1,1],# 宽度方向进行左右个1的padding
         [0,0]]# 色彩通道不进行padding
      ).shape
# 一般图片的padding用在卷积神经网络

TensorShape([4, 30, 30, 3])

# 数据复制
按照某个维度将数据复制n次
tile操作会在内存中真是扩展内存, broadingcast操作并不会真实扩展内存占用
一般推荐使用broadingcast操作

In [21]:
d = tf.random.uniform([2,3],maxval=10,dtype=tf.int32)
print(d)

tf.Tensor(
[[2 8 0]
 [1 5 6]], shape=(2, 3), dtype=int32)


In [22]:
tf.tile(d,[1,2])
# [1,2]中1代表在axis = 0维度上复制一次(相当于不复制)
# 2代表在axis = 1维度上复制2次

<tf.Tensor: id=70, shape=(2, 6), dtype=int32, numpy=
array([[2, 8, 0, 2, 8, 0],
       [1, 5, 6, 1, 5, 6]])>

In [23]:
tf.tile(d,[3,2])

<tf.Tensor: id=72, shape=(6, 6), dtype=int32, numpy=
array([[2, 8, 0, 2, 8, 0],
       [1, 5, 6, 1, 5, 6],
       [2, 8, 0, 2, 8, 0],
       [1, 5, 6, 1, 5, 6],
       [2, 8, 0, 2, 8, 0],
       [1, 5, 6, 1, 5, 6]])>