In [2]:
import tensorflow as tf 
print(tf.constant(1))

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
print(tf.constant(1.))

tf.Tensor(1.0, shape=(), dtype=float32)


In [4]:
print(tf.constant(1.1,dtype = tf.int32))
# 指定数据类型和书籍数据类型不符合,报错

TypeError: Cannot convert 1.1 to EagerTensor of dtype int32

In [5]:
print(tf.constant(1.,dtype = tf.double))

tf.Tensor(1.0, shape=(), dtype=float64)


In [9]:
print(tf.constant([True, False]))
# bool类型的tensor

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [10]:
print(tf.constant('HelloWorld'))
# String类型的tensor

tf.Tensor(b'HelloWorld', shape=(), dtype=string)


In [16]:
with tf.device('cpu'):
    a = tf.constant([1.1])
# CPU上创建一个tensor
    
with tf.device('gpu'):
    b = tf.range(4)
# GPU上创建一个tensor

# GPU上创建的Tensor只能使用GPU的操作, 同样,CPU上创建的tensor只能使用CPU的操作
# 操作是自动判断并执行的

aa = a.gpu()
bb = b.cpu()
# 如果一个运算的两个tensor分布在不同的设备上, 则需要将其中一个tensor移动都另一个设备上
# 保证所有的tensor在一个设备上, 操作才能完成
# 以上方法实现了数据的设备移动

W1027 03:30:29.998017 12440 deprecation.py:323] From <ipython-input-16-93d5a28b69b7>:12: _EagerTensorBase.gpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.identity instead.
W1027 03:30:30.000456 12440 deprecation.py:323] From <ipython-input-16-93d5a28b69b7>:13: _EagerTensorBase.cpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.identity instead.


In [17]:
a.device
# 获取变量的设备信息

'/job:localhost/replica:0/task:0/device:CPU:0'

In [18]:
b.device
# 获取变量的设备信息

'/job:localhost/replica:0/task:0/device:GPU:0'

In [19]:
b.numpy()
# 获取tensor的数据转化为numpy对象(numpy对象一定是在CPU上的)

array([0, 1, 2, 3])

In [20]:
aa.device
# 获取变量的设备信息

'/job:localhost/replica:0/task:0/device:GPU:0'

In [21]:
bb.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [23]:
b.shape
# 获取tensor形状

TensorShape([4])

In [24]:
b.ndim
# 获取tensor的维度
# 向量的维度是1

1

In [25]:
c = tf.constant(1.1)

In [26]:
c.ndim
# 标量的维度是0

0

In [27]:
tf.rank(b)
# 获取b的维度,但是返回的是一个tensor对象

<tf.Tensor: id=20, shape=(), dtype=int32, numpy=1>

In [28]:
tf.rank(tf.ones([3,4,5]))

<tf.Tensor: id=24, shape=(), dtype=int32, numpy=3>

In [35]:
import numpy as np 
d = np.arange(3)

In [36]:
isinstance(a,tf.Tensor)
# 判断一个变量是不是Tensor对象
# 有时候这种方法不能用

True

In [38]:
tf.is_tensor(d)
# TF的专用判断对象是不是tensor对象的方法

False

In [40]:
a.dtype, b.dtype, c.dtype
# 获取tensor数据类型

(tf.float32, tf.int32, tf.float32)

In [43]:
a.dtype == tf.float64
# 判断数据类型

False

In [50]:
# 数据类型转换
# 先创建一个np对象
d = np.arange(3)

In [51]:
d.dtype

dtype('int32')

In [52]:
dd = tf.convert_to_tensor(d)
# 将nunmpy对象转换为tensor,默认使用numpy的数据类型
print(dd)

tf.Tensor([0 1 2], shape=(3,), dtype=int32)


In [53]:
dd = tf.convert_to_tensor(d,dtype=tf.float32)
# 将nunmpy对象转换为tensor,并且换换数据类型
print(dd)

tf.Tensor([0. 1. 2.], shape=(3,), dtype=float32)


In [57]:
# tensor数据类型转换
ddd = tf.cast(dd,dtype=tf.int32)
# 将float32转变为int32
print(ddd)

tf.Tensor([0 1 2], shape=(3,), dtype=int32)


In [60]:
dddd = tf.cast(ddd,dtype=tf.float64)
print(dddd)
print(ddd)
# 将int32转换为float64

tf.Tensor([0. 1. 2.], shape=(3,), dtype=float64)
tf.Tensor([0 1 2], shape=(3,), dtype=int32)


In [61]:
# 整型和布尔型数据的转换

# 整型转化为布尔型
m = tf.constant([0,1])
n = tf.cast(m,dtype=tf.bool)
print(n)

tf.Tensor([False  True], shape=(2,), dtype=bool)


In [63]:
# 布尔型转化为整形
nn = tf.cast(n,dtype=tf.int16)
print(nn)

tf.Tensor([0 1], shape=(2,), dtype=int16)


In [66]:
# tf.Variable对象,一般用于可优化参数
# 将一个tensor转变为Variable之后, 这个参数就自动具有了可求导特性等功能

p = tf.range(5)
q = tf.Variable(p)
print(q.dtype)
print(q.trainable)
# 可训练的

<dtype: 'int32'>
True


In [67]:
isinstance(q,tf.Tensor)
# isinstance判断这个对象已经不是tensor

False

In [69]:
isinstance(q,tf.Variable)

True

In [70]:
tf.is_tensor(q)
# 但是同is_tensor方法, 这个对象还是tensor

True

In [71]:
q.numpy()
# tf.Variable仍然可以通过numpy()方法获取到数据

array([0, 1, 2, 3, 4])

In [74]:
# 创建标量
s = tf.ones([])
print(s)
print(s.numpy())
print(int(s))
print(float(s))

# 标量tensor支持int和float这种数据转换方法
# 这种方法只支持标量形式的tensor

tf.Tensor(1.0, shape=(), dtype=float32)
1.0
1
1.0


#### 创建Tensor
从list或者numpy转换

In [75]:
a1 = tf.convert_to_tensor([1,2],dtype=tf.float32)
print(a1)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [78]:
a2 = tf.convert_to_tensor([[1.],[2]],dtype=tf.float32)
print(a2)

tf.Tensor(
[[1.]
 [2.]], shape=(2, 1), dtype=float32)


In [83]:
b1 = tf.convert_to_tensor(np.ones([3,4]),dtype=tf.float32)
print(b1)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


#### 创建Tensor
直接创建tensor,全1或者全0

In [88]:
c1 = tf.zeros([],dtype=tf.float64)
# 创建一个标量0, 同样可以这是数据类型
print(c1)

tf.Tensor(0.0, shape=(), dtype=float64)


In [85]:
c2 = tf.zeros([1])
# 创建一个向量, 
print(c2)

tf.Tensor([0.], shape=(1,), dtype=float32)


In [86]:
c3 = tf.zeros([3,2])
# 创建一个矩阵
print(c3)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [87]:
c4 = tf.zeros([3,2,3])
# 创建一个3维tensor
print(c4)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 2, 3), dtype=float32)


In [89]:
c5 = tf.zeros_like(c4)
# 创建一个和c4形状大小一样的0tensor
# 这一句等同于 c5 = tf.zeros(c4.shape)
print(c5)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 2, 3), dtype=float32)


#### 创建Tensor
直接创建tensor,全是某一个值, 不一定是0或1

In [90]:
d1 = tf.fill([2,3],9.)
print(d1)

tf.Tensor(
[[9. 9. 9.]
 [9. 9. 9.]], shape=(2, 3), dtype=float32)


#### 创建Tensor
直接创建tensor,随机值

In [92]:
e1 = tf.random.normal([2,3,4], mean=1, stddev=1,dtype=tf.float32)
# mean是设置均值, stddev是设置方差, 这样的正态分布
print(e1)

tf.Tensor(
[[[ 0.46798635  1.8005507   2.012279    1.2001444 ]
  [ 0.7536935   1.1591585   0.94637626  0.46387482]
  [ 2.4931557   1.8524503   2.0053966   1.3324748 ]]

 [[ 1.1139768   1.5913111   0.8870668   1.1189836 ]
  [ 2.0945446   1.6472436   2.1551523   1.8852786 ]
  [ 2.4876218   0.44645208 -0.21458995  0.6591357 ]]], shape=(2, 3, 4), dtype=float32)


In [93]:
e2 = tf.random.truncated_normal([2,2],mean = 1,stddev=1)
# 截断型的正太分布,这样的分布较一般的正态分布, 会降低梯度消失的几率
print(e2)

tf.Tensor(
[[1.7487278  0.10564643]
 [1.8962846  2.2257464 ]], shape=(2, 2), dtype=float32)


In [94]:
e3 = tf.random.uniform([2,2],minval=0,maxval=1)
# 穿件一个均匀分布的tensor
# minval是下限, maxval是上限
print(e3)

tf.Tensor(
[[0.10833848 0.8497865 ]
 [0.63011754 0.11125696]], shape=(2, 2), dtype=float32)


### 样本随机打散

In [96]:
idx = tf.range(64)
print(idx)
idx = tf.random.shuffle(idx)
# 将原本的idx随机打散
print(idx)

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63], shape=(64,), dtype=int32)
tf.Tensor(
[27 40 19 36 17  4 29 52 48 60 13 22 62 35 16  0 30  7 12 39 32 14 11  1
 10 44 58 47 21 63  6 50 31 46 24 33  8  9  5 49 56 34 54 23 41 15 25 53
 38 59  3 43 37 57 26 55 18 45 28 20  2 61 51 42], shape=(64,), dtype=int32)


In [97]:
data_1 = tf.random.uniform([64,784])
label_1 = tf.random.uniform([64],maxval=10,dtype=tf.int32)
# 将上边的随机打散得到的随机索引,应用到真正的数据上
# 保证得到的新的数据和label还是一一对应的
data_2 = tf.gather(data_1,idx)
label_2 = tf.gather(label_1,idx)


#### 创建Tensor
直接创建tensor,constant, 方法类似于ones和zeros方法

In [99]:
tf.constant(1)
# 创建一个标量tensor

<tf.Tensor: id=141, shape=(), dtype=int32, numpy=1>

In [100]:
tf.constant([1])
# 创建一个向量tensor

<tf.Tensor: id=142, shape=(1,), dtype=int32, numpy=array([1])>

In [101]:
tf.constant([[2,3],[3,4]])
# 创建一个矩阵tensor

<tf.Tensor: id=143, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]])>

#### 各种数据使用
标量: loss以及accuracy, shape是()
向量: bias可以理解是一个vector
矩阵: weight可以理解是一个matrix, tensorflow的输入也可以看做一个matrix
三维tensor: 自然语言处理中应用, 输入string数据使用
四维tensor: 图片保存方式[index, height, width, channel]