In [1]:
import tensorflow as tf 
import pandas as pd 
import numpy as np


#### 操作方式
+-*/
**,pow,square
sqrt
//(整除),%(取余)
exp,log
@,matmul(矩阵乘法)
linear layer

#### 操作维度
元素操作
    +-*/
矩阵操作
    @,matmul
维度操作
    reduce_mean,max,min,sum

### 基本操作

In [2]:
a = tf.random.normal([2,2])
b = tf.random.normal([2,2])


In [3]:
a+b

<tf.Tensor: id=12, shape=(2, 2), dtype=float32, numpy=
array([[-1.333833  , -1.8653958 ],
       [ 0.34711277, -0.849319  ]], dtype=float32)>

In [4]:
b//a

<tf.Tensor: id=13, shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  0.],
       [-2., -1.]], dtype=float32)>

In [5]:
b%a

<tf.Tensor: id=14, shape=(2, 2), dtype=float32, numpy=
array([[-0.60431695, -0.1399302 ],
       [-0.16803455, -0.849319  ]], dtype=float32)>

In [10]:
tf.math.log(a)
# 这里的log是数学上得ln,对e取对数
# 没有log10()的接口,利用对数性质来实现log10()

<tf.Tensor: id=19, shape=(2, 2), dtype=float32, numpy=
array([[nan, nan],
       [nan, nan]], dtype=float32)>

In [11]:
tf.exp(a)

<tf.Tensor: id=20, shape=(2, 2), dtype=float32, numpy=
array([[0.4821423 , 0.17809013],
       [0.5974126 , 0.21242487]], dtype=float32)>

In [12]:
b**3

<tf.Tensor: id=22, shape=(2, 2), dtype=float32, numpy=
array([[-0.22069593, -0.0027399 ],
       [ 0.6410839 ,  0.3427765 ]], dtype=float32)>

In [13]:
tf.pow(b,3)

<tf.Tensor: id=24, shape=(2, 2), dtype=float32, numpy=
array([[-0.22069593, -0.0027399 ],
       [ 0.6410839 ,  0.3427765 ]], dtype=float32)>

In [14]:
tf.sqrt(b)

<tf.Tensor: id=25, shape=(2, 2), dtype=float32, numpy=
array([[       nan,        nan],
       [0.9285796 , 0.83656913]], dtype=float32)>

In [15]:
a@b
# 矩阵乘法

<tf.Tensor: id=26, shape=(2, 2), dtype=float32, numpy=
array([[-1.0469413, -1.1054822],
       [-1.0244725, -1.0120966]], dtype=float32)>

In [17]:
tf.matmul(a,b)
# 矩阵乘法

<tf.Tensor: id=28, shape=(2, 2), dtype=float32, numpy=
array([[-1.0469413, -1.1054822],
       [-1.0244725, -1.0120966]], dtype=float32)>

In [19]:
 # 可以对矩阵的某写维度进行矩阵乘法,例如:
c = tf.random.normal([4,2,3])
d = tf.random.normal([4,3,5])

(c@d).shape
# 这里相当于对c的4个子矩阵和d的4个子矩阵进行分写矩阵乘法

TensorShape([4, 2, 5])

In [20]:
# 可以借助broadcasting进行矩阵乘法
m = tf.random.normal([4,2,3])
n = tf.random.uniform([3,5])
nn = tf.broadcast_to(n,[4,3,5])
(m@nn).shape

TensorShape([4, 2, 5])

In [21]:
tf.square(a)
# 平方操作

<tf.Tensor: id=71, shape=(2, 2), dtype=float32, numpy=
array([[0.53219354, 2.9772313 ],
       [0.26537678, 2.399918  ]], dtype=float32)>

In [22]:
a**2

<tf.Tensor: id=73, shape=(2, 2), dtype=float32, numpy=
array([[0.5321936 , 2.9772313 ],
       [0.26537675, 2.399918  ]], dtype=float32)>

In [23]:
tf.pow(a,2)

<tf.Tensor: id=75, shape=(2, 2), dtype=float32, numpy=
array([[0.5321936 , 2.9772313 ],
       [0.26537675, 2.399918  ]], dtype=float32)>