In [1]:
import tensorflow as tf 

#### 据图功能
范数 tf.norm
求最大/最小值 tf.reduce_max/reduce_min
最大/最小值位置 tf.argmin/argmax
相等tf.equal
唯一性tf.unique

#### 向量常规范数操作

In [4]:
a = tf.ones([2,2])

In [5]:
tf.norm(a)

<tf.Tensor: id=18, shape=(), dtype=float32, numpy=2.0>

In [6]:
b = tf.ones([4,28,28,3])

In [7]:
tf.norm(b)

<tf.Tensor: id=26, shape=(), dtype=float32, numpy=96.99484>

In [8]:
#以上的二维范数操作相当于是
tf.sqrt(tf.reduce_sum(tf.square(b)))

<tf.Tensor: id=30, shape=(), dtype=float32, numpy=96.99484>

#### 范数操作(设置范数阶数预计轴向)

In [11]:
tf.norm(a,ord = 2,axis=1)

<tf.Tensor: id=45, shape=(2,), dtype=float32, numpy=array([1.4142135, 1.4142135], dtype=float32)>

#### 取最大/最小值

In [12]:
c = tf.random.normal([4,5])

In [13]:
tf.reduce_max(c), tf.reduce_min(c)
#全局最小/最大

(<tf.Tensor: id=53, shape=(), dtype=float32, numpy=1.8425107>,
 <tf.Tensor: id=55, shape=(), dtype=float32, numpy=-2.2040236>)

In [14]:
tf.reduce_max(c,axis=1)
# 轴向最小/最大

<tf.Tensor: id=57, shape=(4,), dtype=float32, numpy=array([1.2322237 , 0.91676754, 1.3659883 , 1.8425107 ], dtype=float32)>

In [15]:
tf.reduce_max(c,axis=0)

<tf.Tensor: id=59, shape=(5,), dtype=float32, numpy=
array([0.81659144, 0.53468746, 1.3659883 , 1.1753348 , 1.8425107 ],
      dtype=float32)>

#### 取最小/最大值位置

In [16]:
d = tf.random.normal([4,5])

In [20]:
tf.argmax(d)
# 默认是在行向求最值的位置

<tf.Tensor: id=73, shape=(5,), dtype=int64, numpy=array([2, 2, 2, 3, 0], dtype=int64)>

In [21]:
tf.argmax(d,axis=1)

<tf.Tensor: id=75, shape=(4,), dtype=int64, numpy=array([4, 1, 0, 3], dtype=int64)>

#### 判断Tensor各个位置是否相同

In [23]:
e = tf.constant([0,1,2,3,5])
f = tf.range(5)
tf.equal(e,f)
# 返回的tensor都是boolean类型的

<tf.Tensor: id=87, shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True, False])>

#### 去除重复功能

In [24]:
g = tf.constant([2,3,3,4,2])
tf.unique(g)

Unique(y=<tf.Tensor: id=89, shape=(3,), dtype=int32, numpy=array([2, 3, 4])>, idx=<tf.Tensor: id=90, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 2, 0])>)

#### 张量排序
排序ort/argsort
前k个Topk


In [27]:
a = tf.random.shuffle(tf.range(10))
print(a)
tf.sort(a,direction='DESCENDING')

tf.Tensor([2 3 5 7 0 9 6 4 8 1], shape=(10,), dtype=int32)


<tf.Tensor: id=126, shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])>

In [28]:
tf.argsort(a,direction='DESCENDING')
# 得到的分别是从大到小的元素的位置

<tf.Tensor: id=136, shape=(10,), dtype=int32, numpy=array([5, 8, 3, 6, 2, 7, 1, 0, 9, 4])>

In [29]:
x = tf.random.uniform([3,3],maxval=10,dtype=tf.int32)
print(x)

tf.Tensor(
[[5 6 9]
 [4 8 8]
 [9 1 6]], shape=(3, 3), dtype=int32)


In [33]:
tf.sort(x)
# 默认在最后一个维度上进行排序

<tf.Tensor: id=187, shape=(3, 3), dtype=int32, numpy=
array([[5, 6, 9],
       [4, 8, 8],
       [1, 6, 9]])>

In [34]:
tf.sort(x,axis=0)

<tf.Tensor: id=201, shape=(3, 3), dtype=int32, numpy=
array([[4, 1, 6],
       [5, 6, 8],
       [9, 8, 9]])>

# 进行取top-k accuracy的操作应用!!!!!很重要, 计算各个分类的可能性的top-k

In [38]:
res = tf.math.top_k(x,2)
# 一般是在最后一个维度上进行取top操作
# 进行取top-k accuracy的操作应用!!!!!很重要, 计算各个分类的可能性的top-k

In [39]:
res.indices

<tf.Tensor: id=207, shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 2],
       [0, 2]])>

In [40]:
res.values

<tf.Tensor: id=206, shape=(3, 2), dtype=int32, numpy=
array([[9, 6],
       [8, 8],
       [9, 6]])>