In [1]:
 import tensorflow as tf 

## TensorFlow高阶操作
where操作

scatter_nd操作

meshgrid操作


In [ ]:
# 当值传入一个参数的时候,where操作寻找Tensor中的元素为True的位置


In [3]:
a = tf.random.normal([3,3])
print(a)
mask = a > 0
print(mask)

tf.Tensor(
[[-1.3433964   0.7238325  -0.134894  ]
 [-0.4066136  -1.0187474   1.0659574 ]
 [-0.84831846 -0.28372246 -1.2000245 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[False  True False]
 [False False  True]
 [False False False]], shape=(3, 3), dtype=bool)


In [5]:
tf.boolean_mask(a,mask)
# 获取mask中True对应的a中的元素

<tf.Tensor: id=69, shape=(2,), dtype=float32, numpy=array([0.7238325, 1.0659574], dtype=float32)>

In [7]:
tf.where(mask)
# 获取mask中的为True的位置

<tf.Tensor: id=71, shape=(2, 2), dtype=int64, numpy=
array([[0, 1],
       [1, 2]], dtype=int64)>

In [8]:
tf.gather_nd(a,tf.where(mask))
# 这个结果和boolean_mask方法是一样的

<tf.Tensor: id=73, shape=(2,), dtype=float32, numpy=array([0.7238325, 1.0659574], dtype=float32)>

In [9]:
# 当where传入3个参数的时候, 分别是condition, A, B, 三个矩阵大小相同
# condition中该位置判断为True的时候, 返回A中对应位置的值, 反之返回B中对应位置上的值 
tf.where(mask,tf.ones([3,3]),a)

<tf.Tensor: id=77, shape=(3, 3), dtype=float32, numpy=
array([[-1.3433964 ,  1.        , -0.134894  ],
       [-0.4066136 , -1.0187474 ,  1.        ],
       [-0.84831846, -0.28372246, -1.2000245 ]], dtype=float32)>

In [12]:
# scatter_nd 操作根据坐标来进行有目的的更新
indices = tf.constant([[4],[3],[1],[7]])
# 需要更新的位置
updates = tf.constant([9,10,11,12])
# 需要在对应的位置行更新上去的值
shape = tf.constant([8])
# 底板(scatter_nd要求是全0的底板)

In [15]:
tf.scatter_nd(indices,updates,shape)
# 这样获得了一个更新后的底板, 将另一个数组和这个底板进行+或者-可以实现对另一个数组的更新

<tf.Tensor: id=87, shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0, 12])>

In [19]:
# 也可以对立体数组(三维的)进行更新
indices1 = tf.constant([[0],[2]])
# 需要更新的矩阵是一个4,4,4大小的, 这里需要更新0和2位置上的, 而0和2位置上的是一个4*4的矩阵, 所以需要输入对应的4*4的矩阵
update1 = tf.constant([[[5,5,5,5],[6,6,6,6],[7,7,7,7],[8,8,8,8]],
                       [[5,5,5,5],[6,6,6,6],[7,7,7,7],[8,8,8,8]]])
update1.shape

TensorShape([2, 4, 4])

In [20]:
b = tf.constant([4,4,4])
# 这里自动完成了broadingcast
b.shape

TensorShape([3])

In [21]:
tf.scatter_nd(indices1,update1,b)

<tf.Tensor: id=95, shape=(4, 4, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])>

In [27]:
# meshgrid 获取坐标轴系, 一个轴上的好多点
y = tf.linspace(-2.,2.,5)# 从-2到2,一共5个值
x = tf.linspace(-2.,2.,5)# 从-2到2,一共5个值 
point_x,point_y = tf.meshgrid(x,y)

In [28]:
point_x,point_y
# 结合起来正好是一个5*5的点的坐标的x坐标和y坐标

(<tf.Tensor: id=154, shape=(5, 5), dtype=float32, numpy=
 array([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]], dtype=float32)>,
 <tf.Tensor: id=155, shape=(5, 5), dtype=float32, numpy=
 array([[-2., -2., -2., -2., -2.],
        [-1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.]], dtype=float32)>)

In [29]:
tf.stack([point_x,point_y],axis=2) # 在一个[2,5,5]的矩阵上进行stack

<tf.Tensor: id=156, shape=(5, 5, 2), dtype=float32, numpy=
array([[[-2., -2.],
        [-1., -2.],
        [ 0., -2.],
        [ 1., -2.],
        [ 2., -2.]],

       [[-2., -1.],
        [-1., -1.],
        [ 0., -1.],
        [ 1., -1.],
        [ 2., -1.]],

       [[-2.,  0.],
        [-1.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.]],

       [[-2.,  1.],
        [-1.,  1.],
        [ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.]],

       [[-2.,  2.],
        [-1.,  2.],
        [ 0.,  2.],
        [ 1.,  2.],
        [ 2.,  2.]]], dtype=float32)>

In [ ]:
# 这个功能可以用来话等高线以及各种曲线